INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10001, 'Tony', 'Learn Spring!', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10002, 'Tony', 'Learn AWS!', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10003, 'Agatka', 'Learn French!', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10004, 'Agatka', 'Cuddle Antonio', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10005, 'Agatka', 'Massage Antonio', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10006, 'Agatka', 'Kiss Antonio', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10007, 'Agatka', 'Pa-ta-tai Antonio', CURRENT_DATE(), TRUE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10008, 'Tony', 'Kiss Agatka', CURRENT_DATE(), FALSE);